[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "topoprofile"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "geopandas==1.1.4",
    "osm2geojson==0.3.2",
    "pygmt==0.19.0",
    "rioxarray==0.23.0",
    "requests==2.34.2",
    "tqdm==4.70.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-sugar",
    "ruff",
]

[tool.setuptools.packages.find]
include = ["topoprofile*"]
namespaces = false